import type { Job } from "./types";

export const JOBS: Job[] = [
  {
    id: "j-001",
    company: "大手生命保険会社A",
    companyKind: "生命保険",
    position: "商品開発アクチュアリー（第一分野）",
    summary: "主力商品の改定・新商品開発を担う中核ポジション",
    location: "東京都千代田区",
    salary: "年収 700万〜1,400万円",
    salaryMin: 700,
    salaryMax: 1400,
    employmentType: "正社員",
    remote: "一部リモート可",
    tags: ["正会員歓迎", "商品開発", "英語活用", "管理職候補"],
    status: "募集中",
    postedAt: "2026-04-08",
    description:
      "個人保険領域における主力商品の改定および新商品開発をリードするポジションです。保険数理に基づくプライシング、利益性分析、商品スペックの意思決定関与、関連部門との折衝までを一貫して担当いただきます。",
    requirements: [
      "アクチュアリー準会員以上",
      "生命保険会社・コンサル等での商品開発またはバリュエーション実務3年以上",
      "Excel・VBAを用いた計算モデル設計経験",
    ],
    preferred: [
      "第一分野での商品開発経験",
      "IFRS17または経済価値ベース資本規制に関する知見",
      "英語での議論経験",
    ],
    companyOverview:
      "国内最大手の生命保険会社。堅実な財務基盤と成熟した商品開発プロセスを持ち、近年は新領域商品・DX投資にも積極的。",
    workHours: "9:00〜17:00（フレックスタイム制、コアタイムなし）",
    benefits: [
      "各種社会保険完備",
      "確定給付年金・確定拠出年金",
      "住宅補助、通勤手当",
      "アクチュアリー試験受験支援",
      "海外研修制度",
    ],
    holidays: "完全週休2日制、祝日、年末年始、年次有給休暇（初年度17日）",
    selectionProcess: ["書類選考", "一次面接（人事・部門）", "二次面接（部長）", "最終面接（役員）"],
    idealCandidate:
      "数理的裏付けのある商品設計を通じて経営インパクトを生み出したい方、将来的にチームを率いる意志のある方。",
  },
  {
    id: "j-002",
    company: "大手損害保険会社B",
    companyKind: "損害保険",
    position: "数理企画・ERM（経済価値ベース資本管理）",
    summary: "経済価値ベース資本規制対応のコアメンバー",
    location: "東京都千代田区",
    salary: "年収 800万〜1,500万円",
    salaryMin: 800,
    salaryMax: 1500,
    employmentType: "正社員",
    remote: "一部リモート可",
    tags: ["ERM", "ESR", "正会員歓迎", "英語活用"],
    status: "募集中",
    postedAt: "2026-04-12",
    description:
      "経済価値ベースのソルベンシー規制対応、ESR計測、リスク管理プロセスの高度化を担当します。グループ全体のリスク把握と資本配分の実行支援を行うポジションです。",
    requirements: [
      "アクチュアリー準会員以上",
      "損保・生保・再保険・監査法人等での数理実務3年以上",
      "リスク管理・ERMに関心のある方",
    ],
    preferred: [
      "ICS / ESR関連プロジェクト経験",
      "Python、R等での数値分析経験",
      "英語でのグループ会議対応経験",
    ],
    companyOverview:
      "国内メガ損保の一角。グローバル展開を積極化しており、海外子会社を含むグループ全体のリスク・資本管理の高度化が経営テーマ。",
    workHours: "9:00〜17:00（フレックスタイム制）",
    benefits: [
      "各種社会保険",
      "退職金制度",
      "住宅関連補助",
      "アクチュアリー試験支援",
      "グローバル人材研修",
    ],
    holidays: "完全週休2日制、祝日、年末年始、リフレッシュ休暇",
    selectionProcess: ["書類選考", "一次面接", "ケース面接", "最終面接"],
    idealCandidate:
      "規制・経営に近い領域で数理の価値を発揮したい方。リスクと資本の両面から経営を支えたい方。",
  },
  {
    id: "j-003",
    company: "外資系再保険会社C",
    companyKind: "再保険",
    position: "プライシング・アクチュアリー（生保再保険）",
    summary: "生保再保険プライシングの中核ポジション",
    location: "東京都港区",
    salary: "年収 900万〜1,800万円",
    salaryMin: 900,
    salaryMax: 1800,
    employmentType: "正社員",
    remote: "フルリモート可",
    tags: ["外資", "英語必須", "リモート可", "高年収"],
    status: "募集中",
    postedAt: "2026-04-15",
    description:
      "アジア圏の生保再保険プライシングを担当。セディングカンパニーとの交渉、条件設計、プライシングモデル運用までを一貫して担います。",
    requirements: [
      "アクチュアリー正会員または同等の資格保有者",
      "生保再保険または元受生保プライシング経験5年以上",
      "業務レベルの英語（読み書き・会議）",
    ],
    preferred: [
      "SOA / IFoA 資格",
      "アジア市場のビジネス経験",
      "ビジネス開発への関心",
    ],
    companyOverview:
      "世界有数の再保険グループの日本拠点。アジア全域を射程にした生保再保険ビジネスを展開し、プロフェッショナル主義の文化。",
    workHours: "フレックスタイム制、コアタイム10:00-15:00",
    benefits: [
      "各種社会保険",
      "RSU等インセンティブ",
      "フルリモート",
      "グローバルモビリティ制度",
    ],
    holidays: "完全週休2日制、祝日、年末年始、年次有給休暇",
    selectionProcess: ["書類選考", "HR面接", "技術面接（英語含む）", "グローバル最終面接（英語）"],
    idealCandidate:
      "グローバル環境でプロフェッショナルとして成長したい方。専門性と交渉力の両立を目指す方。",
    isConfidential: true,
  },
  {
    id: "j-004",
    company: "大手戦略コンサルD",
    companyKind: "コンサル",
    position: "アクチュアリアル・アドバイザリー（シニアアソシエイト）",
    summary: "保険会社向け数理コンサル。規制対応〜DXまで。",
    location: "東京都千代田区",
    salary: "年収 850万〜1,600万円",
    salaryMin: 850,
    salaryMax: 1600,
    employmentType: "正社員",
    remote: "一部リモート可",
    tags: ["コンサル", "ERM", "IFRS17", "英語活用"],
    status: "募集中",
    postedAt: "2026-04-05",
    description:
      "国内外の保険会社を対象に、数理・ERM・IFRS17・経済価値評価・保険DXなどを横断する高付加価値コンサルティングに従事いただきます。",
    requirements: [
      "アクチュアリー準会員以上",
      "保険数理実務3年以上、またはBig4系アクチュアリー経験",
      "プロジェクトベースの業務推進経験",
    ],
    preferred: [
      "IFRS17プロジェクト経験",
      "英語での成果物作成・会議対応",
      "ERM / ESR 実務経験",
    ],
    companyOverview:
      "グローバルネットワークを持つ大手コンサルティングファーム。保険業界を担当する専門部隊を有し、高度な数理・リスク・経営コンサルを提供。",
    workHours: "フレックスタイム制",
    benefits: [
      "各種社会保険",
      "昇進に連動したインセンティブ",
      "海外オフィス異動制度",
      "資格支援",
    ],
    holidays: "完全週休2日制、祝日、年末年始、有給",
    selectionProcess: ["書類選考", "ケース面接×2", "パートナー面接", "オファー面談"],
    idealCandidate:
      "複数クライアントの課題解決を通じて圧倒的な成長カーブを描きたい方。",
  },
  {
    id: "j-005",
    company: "中堅生命保険会社E",
    companyKind: "生命保険",
    position: "バリュエーション・アクチュアリー",
    summary: "責任準備金評価・ソルベンシー報告業務",
    location: "東京都新宿区",
    salary: "年収 650万〜1,100万円",
    salaryMin: 650,
    salaryMax: 1100,
    employmentType: "正社員",
    remote: "一部リモート可",
    tags: ["バリュエーション", "準会員歓迎", "落ち着いた環境"],
    status: "募集中",
    postedAt: "2026-04-01",
    description:
      "責任準備金評価および各種ソルベンシー関連報告の実務を担当。将来的には部門のサブリーダーとしてチームマネジメントも担っていただきます。",
    requirements: [
      "アクチュアリー研究会員以上",
      "生保バリュエーション実務2年以上",
      "Excel / VBA / SQL いずれかの実務経験",
    ],
    preferred: ["管理会計・経営企画の経験", "準会員または正会員"],
    companyOverview:
      "特定マーケットに強みを持つ中堅生保。長期にわたる堅実経営と落ち着いた社風が特徴。",
    workHours: "9:00〜17:30（フレックスあり）",
    benefits: ["各種社会保険", "確定給付年金", "受験支援", "住宅手当"],
    holidays: "完全週休2日制、祝日、年末年始、有給",
    selectionProcess: ["書類選考", "一次面接", "最終面接"],
    idealCandidate:
      "腰を据えてバリュエーション実務を深めたい方、将来的にマネジメントも視野に入れている方。",
  },
  {
    id: "j-006",
    company: "信託銀行F 年金数理部",
    companyKind: "年金",
    position: "年金アクチュアリー",
    summary: "企業年金の数理計算・コンサルティング",
    location: "東京都中央区",
    salary: "年収 700万〜1,300万円",
    salaryMin: 700,
    salaryMax: 1300,
    employmentType: "正社員",
    remote: "一部リモート可",
    tags: ["年金", "コンサル要素", "正会員歓迎"],
    status: "募集中",
    postedAt: "2026-03-28",
    description:
      "企業年金制度の数理計算、制度設計コンサルティング、お客さま折衝を担当します。数理と経営の橋渡しポジションです。",
    requirements: [
      "企業年金または関連実務3年以上",
      "アクチュアリー準会員以上（もしくは年金数理人志望）",
    ],
    preferred: ["顧客折衝経験", "年金数理人資格取得意向"],
    companyOverview:
      "国内有数の信託銀行。企業年金の受託件数で業界上位に位置するリーディングプレイヤー。",
    workHours: "9:00〜17:00",
    benefits: ["各種社会保険", "企業年金", "住宅補助", "資格支援"],
    holidays: "完全週休2日制、祝日、年末年始",
    selectionProcess: ["書類選考", "一次面接", "最終面接"],
    idealCandidate:
      "数理の専門性を活かしながらお客さまの制度設計に踏み込みたい方。",
  },
  {
    id: "j-007",
    company: "外資系コンサルG",
    companyKind: "コンサル",
    position: "Insurance Analytics / Data Scientist（数理バックグラウンド歓迎）",
    summary: "保険×データサイエンスで新しい価値を生み出す",
    location: "東京都港区",
    salary: "年収 800万〜1,500万円",
    salaryMin: 800,
    salaryMax: 1500,
    employmentType: "正社員",
    remote: "フルリモート可",
    tags: ["データサイエンス", "Python", "英語活用", "リモート可"],
    status: "募集中",
    postedAt: "2026-04-10",
    description:
      "保険会社向けの高度アナリティクス・データサイエンスプロジェクトを推進。料率モデル、顧客分析、フロード検知等を担当します。",
    requirements: [
      "数理・統計・計算機科学系バックグラウンド",
      "Python等でのデータ分析経験3年以上",
    ],
    preferred: [
      "保険数理実務経験",
      "機械学習の業務適用経験",
      "英語でのコミュニケーション",
    ],
    companyOverview:
      "世界有数の戦略＋テックコンサル。保険領域のアナリティクスチームを拡張中。",
    workHours: "フレックスタイム",
    benefits: ["各種社会保険", "RSU", "フルリモート", "資格・学習支援"],
    holidays: "完全週休2日制、祝日",
    selectionProcess: ["書類選考", "コーディング / ケース面接", "最終面接（英語）"],
    idealCandidate: "保険数理とデータサイエンスの両輪を伸ばしたい方。",
  },
  {
    id: "j-008",
    company: "大手生命保険会社H",
    companyKind: "生命保険",
    position: "ALM・運用アクチュアリー（若手歓迎）",
    summary: "負債特性を踏まえた資産運用戦略の立案",
    location: "東京都港区",
    salary: "年収 600万〜1,100万円",
    salaryMin: 600,
    salaryMax: 1100,
    employmentType: "正社員",
    remote: "一部リモート可",
    tags: ["ALM", "若手歓迎", "研究会員歓迎"],
    status: "募集中",
    postedAt: "2026-03-25",
    description:
      "生保負債特性を踏まえたALM戦略の立案、運用部門との連携、資本効率向上施策の提案を担当します。",
    requirements: [
      "アクチュアリー研究会員以上",
      "生保数理または運用に関連する実務経験1年以上",
    ],
    preferred: ["ALM関連経験", "CFAへの関心"],
    companyOverview: "国内トップクラスの生命保険会社。ALM組織の強化を進めている。",
    workHours: "9:00〜17:00",
    benefits: ["各種社会保険", "退職金", "住宅補助", "受験支援"],
    holidays: "完全週休2日制",
    selectionProcess: ["書類選考", "一次面接", "最終面接"],
    idealCandidate: "資産・負債の両面から保険経営を捉えたい若手アクチュアリー。",
  },
  {
    id: "j-009",
    company: "非公開（大手損保系列）",
    companyKind: "損害保険",
    position: "プライシング・アクチュアリー（自動車保険）",
    summary: "自動車保険料率の高度化プロジェクト",
    location: "東京都新宿区",
    salary: "年収 750万〜1,300万円",
    salaryMin: 750,
    salaryMax: 1300,
    employmentType: "正社員",
    remote: "一部リモート可",
    tags: ["損保", "プライシング", "GLM", "データ活用"],
    status: "募集中",
    postedAt: "2026-04-03",
    description:
      "自動車保険の料率改定プロジェクトをリード。GLM等の数理モデルを用いた料率構築と運用を担います。",
    requirements: [
      "損保プライシング実務2年以上",
      "GLMなどの予測モデルに関する知見",
    ],
    preferred: ["準会員以上", "テレマティクス関連の知見"],
    companyOverview: "国内大手損保グループの基幹会社。",
    workHours: "9:00〜17:00",
    benefits: ["各種社会保険", "退職金", "住宅関連補助"],
    holidays: "完全週休2日制",
    selectionProcess: ["書類選考", "一次面接", "最終面接"],
    idealCandidate: "データに基づく料率設計で事業貢献したい方。",
    isConfidential: true,
  },
  {
    id: "j-010",
    company: "ITスタートアップI",
    companyKind: "その他",
    position: "保険ドメイン・プロダクトアナリスト（数理バックグラウンド）",
    summary: "保険×テクノロジー領域での商品開発",
    location: "東京都渋谷区",
    salary: "年収 700万〜1,300万円",
    salaryMin: 700,
    salaryMax: 1300,
    employmentType: "正社員",
    remote: "フルリモート可",
    tags: ["スタートアップ", "リモート可", "未経験歓迎", "保険DX"],
    status: "募集中",
    postedAt: "2026-04-14",
    description:
      "保険業界の既存プレイヤーと共に新しいプロダクトをつくるスタートアップにて、保険ドメインアナリストとしてプロダクト設計・数値設計を担当。",
    requirements: ["数理・統計・保険数理の基礎知識", "プロダクトへの強い関心"],
    preferred: ["研究会員以上", "スタートアップ志向"],
    companyOverview: "保険DXを切り口にした成長スタートアップ。",
    workHours: "フレックスタイム",
    benefits: ["ストックオプション", "フルリモート", "学習支援"],
    holidays: "完全週休2日制",
    selectionProcess: ["書類選考", "カジュアル面談", "面接×2"],
    idealCandidate: "既存の保険業界の常識に囚われずに新しい価値を創りたい方。",
  },
  {
    id: "j-011",
    company: "大手生命保険会社J",
    companyKind: "生命保険",
    position: "第三分野商品アクチュアリー",
    summary: "医療・がん保険領域の商品開発を担う",
    location: "東京都新宿区",
    salary: "年収 700万〜1,300万円",
    salaryMin: 700,
    salaryMax: 1300,
    employmentType: "正社員",
    remote: "一部リモート可",
    tags: ["第三分野", "商品開発", "準会員歓迎"],
    status: "募集中",
    postedAt: "2026-03-20",
    description:
      "医療保険・がん保険などの第三分野領域における商品開発、プライシング、収支モニタリングを担当します。",
    requirements: ["第三分野数理実務経験", "研究会員以上"],
    preferred: ["準会員以上", "商品開発マネジメント経験"],
    companyOverview: "第三分野に強みを持つ生保グループ。",
    workHours: "9:00〜17:00",
    benefits: ["各種社会保険", "退職金", "住宅補助"],
    holidays: "完全週休2日制",
    selectionProcess: ["書類選考", "一次面接", "最終面接"],
    idealCandidate: "第三分野領域で商品開発の専門家を目指す方。",
  },
  {
    id: "j-012",
    company: "外資系生命保険K",
    companyKind: "生命保険",
    position: "Appointed Actuary Office",
    summary: "保険計理人業務のサポート",
    location: "東京都港区",
    salary: "年収 1,000万〜1,800万円",
    salaryMin: 1000,
    salaryMax: 1800,
    employmentType: "正社員",
    remote: "一部リモート可",
    tags: ["外資", "正会員", "高年収", "英語活用"],
    status: "募集終了",
    postedAt: "2026-03-10",
    description:
      "保険計理人オフィスにて、チーフアクチュアリーを補佐し、各種検証業務・レポーティングを担います。",
    requirements: ["アクチュアリー正会員", "生保数理実務8年以上", "業務英語"],
    preferred: ["保険計理人補佐経験"],
    companyOverview: "外資系大手生命保険会社日本法人。",
    workHours: "フレックスタイム",
    benefits: ["各種社会保険", "RSU", "海外研修"],
    holidays: "完全週休2日制",
    selectionProcess: ["書類選考", "面接×3", "レファレンス"],
    idealCandidate: "将来チーフアクチュアリーを目指したい正会員。",
  },
];

export const JOB_KINDS = [
  "生命保険",
  "損害保険",
  "再保険",
  "コンサル",
  "信託銀行",
  "年金",
  "その他",
] as const;

export const POPULAR_TAGS = [
  "生命保険",
  "損害保険",
  "再保険",
  "コンサル",
  "未経験歓迎",
  "リモート可",
  "正会員歓迎",
  "英語活用",
];

export function getJob(id: string): Job | undefined {
  return JOBS.find((j) => j.id === id);
}
